Feature/login
Travel-Troupe/back pull request #3
Opened 2021-11-11 21:01 UTC by NaouelZ

2021-11-13 17:23 UTC, Punkte requested changes

2021-11-13 17:23 UTC, Punkte commented on src/routes/auth.js
> +import router from './index.js'
Utilise plutôt une nouvelle instance de `Router`
```javascript 
import { Router } from 'express'

const router = Router()
```

2021-11-13 17:23 UTC, Punkte commented on src/app.js
> +
Possible de séparer ca dans un autre fichier ? 🙏🏾

2021-11-13 17:23 UTC, Punkte commented on src/app.js
> +}
Pareil si tu peux exporter ca dans le même fichier qui exporterai passport

2021-11-13 17:23 UTC, Punkte commented on src/app.js
> +      process.env.AUTH0_CALLBACK_URL || 'http://localhost:5000/callback'
```
`http://localhost:${process.env.API_PORT || 5000}/callback`
````

ou alors tu peux exporter la variable `PORT` qu'il y'a dans le fichier server.js

2021-11-13 17:28 UTC, NaouelZ commented on src/app.js
> +
ça, c'est à dire ?

2021-11-13 17:30 UTC, Punkte commented on src/app.js
> +
Toute la partie passport et strategy

2021-11-13 18:05 UTC, Punkte commented on src/routes/auth.js
> +    util.format('https://%s/v2/logout', process.env.AUTH0_DOMAIN)
S'il y'a des variables d'environnement à ajouter tu peux les mettres dans le `.env.example` et aussi l'ajouter au `docker-compose.yml` please ? 🙏🏾

2021-11-13 18:05 UTC, Punkte commented on src/routes/auth.js
> +    util.format('https://%s/v2/logout', process.env.AUTH0_DOMAIN)
Pas en clair mais mets des trucs bidons, tu m'enverras les vrais variables par message lol

2021-11-21 20:45 UTC, Punkte approved these changes

2021-11-21 21:26 UTC, merged